### ISSUE TITLE
五笔自定义词库不生效

### ISSUE THREAD

**Issue by jiutianhuanpei** [KyleBing/rime-wubi86-jidian#1]
在 wubi86_jidian_user.dict 里新增词汇，不生效
不新增词汇，自带的 vetp 也不生效

**Comment by KyleBing** [comment]
已修复，是我误写成了空格，应该是 tab

**Comment by jiutianhuanpei** [comment]
还是不行，我重新check 了一份，完全替换之后还是不生效

**Comment by KyleBing** [comment]
> 还是不行，我重新check 了一份，完全替换之后还是不生效

又是我的错 😂，词条后面不能写注释，需要另起一行。好了。

**Comment by jiutianhuanpei** [comment]
谢谢，解决了 😁
