### ISSUE TITLE
单字输出模式下，可以实现输出自定义短语吗？

### ISSUE THREAD

**Issue by superLei** [KyleBing/rime-wubi86-jidian#100]
五笔开启单字输出模式，可以实现输出自定义短语吗？
目前我看是会过滤所有的输出，不会有单独的短语输出功能。

**Comment by KyleBing** [comment]
对，如果有能力，可以按条件过滤。
比如你添加了一个短语，短语的结尾添加一个标识符，在 lua 中过滤候选词，判断是否存在 标识符，如果存在就输出并去掉标识符，如果不存在，就输出单字。

**Comment by superLei** [comment]
> 对，如果有能力，可以按条件过滤。 比如你添加了一个短语，短语的结尾添加一个标识符，在 lua 中过滤候选词，判断是否存在 标识符，如果存在就输出并去掉标识符，如果不存在，就输出单字。

好的，感谢提供的思路。👍
