### ISSUE TITLE
选中候选词背景长度

### ISSUE THREAD

**Issue by offferu** [KyleBing/rime-wubi86-jidian#103]
<img src=https://i.postimg.cc/KczwQqbZ/wubi.png>

请问设置何种参数可使候选字的背景拉长？如图所示

**Comment by KyleBing** [comment]
macOS Windows 两个对应的皮肤编辑文件分别在 下面两个文件中，具体的参数有注释，可以了解一下：

https://github.com/KyleBing/rime-wubi86-jidian/blob/master/squirrel.custom.yaml
https://github.com/KyleBing/rime-wubi86-jidian/blob/master/weasel.custom.yaml

**Comment by offferu** [comment]
非常感谢！原来跟hilite_padding，hilite_spacing，margin_x，margin_y有关系，现在调的差不多了 :) 
![屏幕截图 2024-05-07 111628](https://github.com/KyleBing/rime-wubi86-jidian/assets/34037165/37cc5613-79a5-49c2-b9ef-9f29de61f181)
