### ISSUE TITLE
五笔拼音如何设置单字优先？

### ISSUE THREAD

**Issue by TomatoFryEggs** [KyleBing/rime-wubi86-jidian#105]
目前只能在纯五笔模式中看到有单字优先模式，五笔拼音仿该方法设置后没有生效。

**Comment by thincen** [comment]
我觉得是生效了的呢，你看这个算吗![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/67512282/e0b56b2b-3d89-464e-990f-a592ba4366db)
