### ISSUE TITLE
求教大佬，如何在中文输入模式下输入省略号和破折号

### ISSUE THREAD

**Issue by tiange1949** [KyleBing/rime-wubi86-jidian#110]
### 问题描述

**系统**：macOS Ventura 13.5.2

**Rime version:** 1.8.5 (Squirrel)

**输入方案**：wubi86_jidian.schema

> 在以上系统版本和软件配置下，选择五笔86极点方案，在中文输入模式下无法输入省略号和破折号。

按下`Shift` + `6` ，如下图：

![image-20231221210954065](https://cdn.jsdelivr.net/gh/tiange1949/Image-hosting-service/2023%E5%9B%BE%E5%BA%8A/image-20231221210954065.png)

按下按下`Shift` + `-` ，如下图：

![image-20231221211055043](https://cdn.jsdelivr.net/gh/tiange1949/Image-hosting-service/2023%E5%9B%BE%E5%BA%8A/image-20231221211055043.png)

### 定位过程

点击鼠须管输入法图标，点击`Settings`，进入方案设置文件夹

<img src="https://cdn.jsdelivr.net/gh/tiange1949/Image-hosting-service/2023%E5%9B%BE%E5%BA%8A/image-20231221211403740.png" alt="image-20231221211403740" style="zoom:33%;" />

使用 VSCode 打开`default.custom.yaml`文件，定位到**147**和**148**行

![image-20231221211722209](https://cdn.jsdelivr.net/gh/tiange1949/Image-hosting-service/2023%E5%9B%BE%E5%BA%8A/image-20231221211722209.png)

**Comment by KyleBing** [comment]
是否还包含有其它方案的文件？

**Comment by tiange1949** [comment]
> 是否还包含有其它方案的文件？

<img width="772" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/26919925/b73e4688-6392-4ac8-9d33-efd6cf24e9d9">

上图是我的`Settings`文件夹目录，输入方案是该仓库的默认几种方案，我用的是`wubi86_jidian.schema`，不知道为什么无法输出省略号和破折号。

**Comment by tiange1949** [comment]
> 是否还包含有其它方案的文件？

**macOS卸载Squirrel输入法再重新安装，然后打开settings文件夹，点击`macOS-双击复制文件内容.command`后再修改码表，单字输入正常，破折号和省略号都能够正常输入**

猜想可能是之前其他方案污染了相关文件，导致不能输入省略号和破折号。

但是在windows下无法使用这种方法，因为windows安装过程中至少要选择一种输入方案，Rime不是纯净的未部署的文件夹，这时将wubi86-jidian方案复制到Rime文件夹下依然出现这个问题，目前还未找到问题原因和解决方法。

![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/26919925/d5ab2c9f-dc2f-4b36-9f8b-1e48bbc64800)

**Comment by KyleBing** [comment]
把 Rime 文件夹清空再把东西复制进去就可以了。

**Comment by tiange1949** [comment]
> 把 Rime 文件夹清空再把东西复制进去就可以了。

还能这样操作吗，我以为bulid文件夹必须保留呢，所以都是将wubi86-jidian文件夹复制到Rime文件夹的，然后选择替换同名文件夹，感觉这是正确的方法，我明天上班试试

**Comment by KyleBing** [comment]
嗯，build 文件夹里面的是程序认的东西，它是根据 Rime 目录里文件生成的。

**Comment by tiange1949** [comment]
**问题复现：**
在`wubi86_jidian.schema`文件中选择纯单字就会出现这种情况

**定位原因：**
系统没有安装 Lua 软件，无法运行`***.lua`脚本

**解决方法：**

1. 系统下载 Lua 并安装；
2. 删除 Rime 文件夹下的所有文件；
3. 将 `wubi86-jidian-master`下所有文件复制到 `Rime` 文件夹下； 
4. 重新部署即可；
5. 中文单字输入模式下输出省略号和破折号；

**Comment by tiange1949** [comment]
> **问题复现：** 在`wubi86_jidian.schema`文件中选择纯单字就会出现这种情况
> 
> **定位原因：** 系统没有安装 Lua 软件，无法运行`***.lua`脚本
> 
> **解决方法：**
> 
> 1. 系统下载 Lua 并安装；
> 2. 删除 Rime 文件夹下的所有文件；
> 3. 将 `wubi86-jidian-master`下所有文件复制到 `Rime` 文件夹下；
> 4. 重新部署即可；
> 5. 中文单字输入模式下输出省略号和破折号；

**Lua已经安装，选择纯单字模式还是会出现这种情况，关闭单字又能正常输入省略号和破折号了。**
![image](https://github.com/user-attachments/assets/688c70dd-bac6-491d-8c27-b728973befd5)
