### ISSUE TITLE
词语权重bug

### ISSUE THREAD

**Issue by ideazh** [KyleBing/rime-wubi86-jidian#111]
系统：Ubuntu 20.04
ibus-rime版本：1.4.0（版本没跟上但用起来一切正常）
![屏幕截图](https://github.com/KyleBing/rime-wubi86-jidian/assets/26226823/4de054c5-6add-4321-8b63-988b3e09b44f)
以上是系统词库wubi86_jidian.dict.yaml的截图，这4个词似乎忽略了权重，并且我在用户词库wubi86_jidian_user.dict.yaml中添加一个权重为100的词并没有在候选中排第一，请问这是软件bug还是配置有问题呢？感谢！

**Comment by KyleBing** [comment]
输入的编码不完整，当编码唯一时才有效，这属于正在输入中。

**Comment by ideazh** [comment]
谢谢你的回复，确实输入4个编码才生效。
