### ISSUE TITLE
更新码表后输出日期和时间的命令失效

### ISSUE THREAD

**Issue by chinliangwang** [KyleBing/rime-wubi86-jidian#113]
最近换了新电脑，安装了最新版本后，我在wubi86_jidian.dict文件里替换了自己常用的码表，但替换完成后发现date\time等快捷命令失效了，输出的内容如下图，请问我要怎么解决？
<img width="646" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/16532953/3e57dcbe-0d8b-4658-a9be-e52a286202a0">

**Comment by KyleBing** [comment]
这个不太清楚，可能是没有 lua 支持？
试着下载一下试试 https://sourceforge.net/projects/luabinaries/files/5.4.2/

**Comment by chinliangwang** [comment]
> 这个不太清楚，可能是没有 lua 支持？ 试着下载一下试试 https://sourceforge.net/projects/luabinaries/files/5.4.2/

如果没有lua支持的话能正常使用默认配置吗？我现在使用的你默认配置的码表是没问题的，就很奇怪。其它什么地方都没改，只改了码表

**Comment by KyleBing** [comment]
这部分代码，它是调用的 lua 脚本，用的根目录下的 [rime.lua](https://github.com/KyleBing/rime-wubi86-jidian/blob/master/rime.lua)

**Comment by tiange1949** [comment]
<img width="890" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/26919925/6054bd36-4c0d-4445-91f2-4800fb2addb0">
 

<img width="355" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/26919925/daa803ec-28d4-4ef2-8d34-d6b1b547bd8a">


<img width="612" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/26919925/e87d273d-6c98-4116-8015-3acf6c6a6105">



- macOS 安装 Lua 后，输出日期和时间的命令可以了，感谢题主提出的问题和老哥的回答，建议仓库 **Readme** 增加需要 Lua 依赖的说明，要不然小白找半天也没发现问题所在……

**Comment by KyleBing** [comment]
> <img alt="image" width="890" src="https://private-user-images.githubusercontent.com/26919925/294897460-6054bd36-4c0d-4445-91f2-4800fb2addb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjI1OTMsIm5iZiI6MTcwNDcyMjI5MywicGF0aCI6Ii8yNjkxOTkyNS8yOTQ4OTc0NjAtNjA1NGJkMzYtNGMwZC00NDQ1LTkxZjItNDgwMGZiMmFkZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzNTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MTdkNGMwNzBlMmEzMWIxOGM0Y2QzNDY4ZjljM2Y0N2JjYjE0NWVjNjliODQxZTllMTk3MmFjMmYwYTkwNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qUUgFhpo1OtCOHBuWavP9DeoN2-G995kPcfM6RZg5Ak"> <img alt="image" width="355" src="https://private-user-images.githubusercontent.com/26919925/294898240-daa803ec-28d4-4ef2-8d34-d6b1b547bd8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjI1OTMsIm5iZiI6MTcwNDcyMjI5MywicGF0aCI6Ii8yNjkxOTkyNS8yOTQ4OTgyNDAtZGFhODAzZWMtMjhkNC00ZWYyLThkMzQtZDZiMWI1NDdiZDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzNTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDQxNmRkMGNlOWI5ZmRkNjIzMDg1MjVlZDg3NWQ1ZDllMDgwYTdmMjc3ZjVmODkzODhiOGMzODExZGM2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I-BnZRAzXYiT_yGfZ18Buu1fPh95Ir_g1vq8lKkwt-k"> <img alt="image" width="612" src="https://private-user-images.githubusercontent.com/26919925/294898371-e87d273d-6c98-4116-8015-3acf6c6a6105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjI1OTMsIm5iZiI6MTcwNDcyMjI5MywicGF0aCI6Ii8yNjkxOTkyNS8yOTQ4OTgzNzEtZTg3ZDI3M2QtNmM5OC00MTE2LTgwMTUtM2FjZjZjNmE2MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzNTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzVhM2VhNDM1YThhZTM3YTY3Nzg1ODdkMjczNDU1NWIwZmVkODFjNzA0ZjVjN2I5ZjI5NTZjZjc5YTYwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Usbf6Q1E5wJ-h3fBoXuZjVRI8RjT7cGo5C7Ns343gk0">
> * macOS 安装 Lua 后，输出日期和时间的命令可以了，感谢题主提出的问题和老哥的回答，建议仓库 **Readme** 增加需要 Lua 依赖的说明，要不然小白找半天也没发现问题所在……

可以，之前我也不知道，现在知道了。

**Comment by redleafnew** [comment]
> 最近换了新电脑，安装了最新版本后，我在wubi86_jidian.dict文件里替换了自己常用的码表，但替换完成后发现date\time等快捷命令失效了，输出的内容如下图，请问我要怎么解决？ <img alt="image" width="646" src="https://private-user-images.githubusercontent.com/16532953/294802048-3e57dcbe-0d8b-4658-a9be-e52a286202a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Nzk4MjYsIm5iZiI6MTcwNTk3OTUyNiwicGF0aCI6Ii8xNjUzMjk1My8yOTQ4MDIwNDgtM2U1N2RjYmUtMGQ4Yi00NjU4LWE5YmUtZTUyYTI4NjIwMmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAzMTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzYzYzE2YmNjZTQ2ZWRlYmIzN2NmODNlYzc5NTQzZmE1OTUzMmI4ZjZmNTc2ODA4ZjI5ZGMzZDU3NTM1ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lyy_D5tv_hAZNYr7lXRi9T46Xdv8-fnw-9gvrM8-pBI">

我大概知道是怎么回事，与码表有关。
你在码表中搜索date\time，它对应的就是这些内容。
在原来输入法中可以处理这些$n$y之类的代码，但在RIME中不行了，删除即可。
