### ISSUE TITLE
rtt编码有一个未知字符

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [KyleBing/rime-wubi86-jidian#115]
rtt编码有一个未知字符：

![2024-01-12-215058|500](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2024/01/12/2024-01-12-215058|500.png)

查询码表后，发现也是未知：

![2024-01-12-215123|500](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2024/01/12/2024-01-12-215123|500.png)

直接查询源文件：

![2024-01-12-215207|500](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2024/01/12/2024-01-12-215207|500.png)

所以这是啥？是我的字体显示不出来（macOS自带的苹方），还是说就是有个问题？

**Comment by Lawrence-of-AnKing** [comment]
通过查询，得到其原因：

Rime 默认采用大字符集，但不是所有字体都为这些额外字符设计了字体，如 macOS 自带的就没有。

要么更换大字符集的字体，要么就过滤掉这些额外字符，参考解决方案：[解决](https://placeless.net/blog/uncommon-chinese-character-in-rime)。

大致上是随着 Rime 的更新，增加了一个字符集过滤功能，可以通过切换UTF-8这种大字符集到GBK这种小字符集，过滤掉那些八百年用不到的生僻字：

```yaml
  engine/filters:
      - charset_filter@gbk            # (※3) 默认 GBK 
```

更有大佬考虑到 Emoji 无法与 GBK 共存的问题，提交了 `@gbk + emoji` 的方式。

但是很坑的是，[#59](https://github.com/rime/librime/issues/59)中提到：

<img width="974" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/22313057/a070c880-4b62-4034-aa49-add80d4318c3">

后续的更新中删除了此方案，变成了一个插件，所以方案无效。

请问还有啥方法过滤掉这些不常用的字符吗？

**Comment by bczhc** [comment]
顺便说一下这个字是私人使用区里的，没相应且正确的字体就显示不出很正常。
```
character  byte       UTF-32   encoded as     glyph   name
        0          0  00E815   EE A0 95             Unknown character in range Private Use Area
```

一般码表中是不放PUA字的……

**Comment by Lawrence-of-AnKing** [comment]
> 顺便说一下这个字是私人使用区里的，没相应且正确的字体就显示不出很正常。
> 
> ```
> character  byte       UTF-32   encoded as     glyph   name
>         0          0  00E815   EE A0 95             Unknown character in range Private Use Area
> ```
> 
> 一般码表中是不放PUA字的……

这个字表来自 https://github.com/KyleBing/rime-wubi86-jidian ，据说是极点的字表。

要说为啥这些码表也放这些生僻字，只能说Rime本来就是设计给繁体字使用者，用这个输入法的人也都比较偏执，可能追求盲目且对普通人没啥意义的大而全吧。

另一个微软的字表就正常许多了：https://github.com/networm/Rime。

目前是直接用这个微软词库，纯单字模式，然后维护一个个人词库，用来放词语，挂载在后面，算是曲线救国。

那些生僻字直接放弃，反正我这辈子可能都用不到一次，留在词库里的性价比低到发指。

**Comment by bczhc** [comment]
生僻字每个人需求不一样，当然大多数人一辈子都不会用到几个。事实上现在新的输入方案很多都有大字集（一直到扩展I区的那种），跟Rime的设计什么繁体不繁体的无关。正所谓“我不能不用，但你不能没有”……大字集只是在需要用到时开启，一般开启过滤。

```
~ ❯ fc-match :charset=E815                                                                                     14:32:49
FZSongS_20100603.TTF: "FZSongS-Extended" "Regular"
```

顺便，我看了一下这个是方正宋体大字集字体里的PUA玩意。
![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/49330580/baeb08a5-e339-4c9a-b35d-783cbe1d8025)

**Comment by bczhc** [comment]
如果使用lua，过滤法可以相当自定义：

https://github.com/bczhc/rime-config/blob/18bcabf8d81731bfaa80d58d347120741ec82bfd/lua/tiger_core2022_filter.lua#L51-L84

**Comment by KyleBing** [comment]
生僻字，跟字体有关，你使用的字体里没有这个字符的字面形状。无所谓，不需要可以删除这个字。不推荐再使用生僻字。

![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/ceeca538-d306-4940-b34b-233a27ae20eb)
