### ISSUE TITLE
能不能出一个支持新世纪的版本

### ISSUE THREAD

**Issue by redleafnew** [KyleBing/rime-wubi86-jidian#117]
RT
感谢。
我知道有这个：
https://github.com/GuoBinyong/wubixinshiji

**Comment by KyleBing** [comment]
不需要支持，直接拖进来用就可以了。
在 default.custom.yaml 文件中添加需要添加的码表的名字，在输入法中进行切换使用就可以了。
或者直接替换掉里面的内容。

https://github.com/KyleBing/rime-wubi86-jidian/blob/master/default.custom.yaml#L11C3-L11C14

**Comment by KyleBing** [comment]
弄了个分支，从网上找了个新世纪的码表，将目前码表中的字词根据新世纪的编码重新生成了一下，你可以试试能不能用。后续告诉我有没有编码不对的。

https://github.com/KyleBing/rime-wubi86-jidian/tree/%E6%96%B0%E4%B8%96%E7%BA%AA

**Comment by redleafnew** [comment]
多谢，多谢。
