### ISSUE TITLE
怎么设置简入繁出？

### ISSUE THREAD

**Issue by bosconb** [KyleBing/rime-wubi86-jidian#12]
自己揣摩着应该是用wubi_trad.schema.yaml方案输出繁体吧，于是自己补上wubi86.dict.yaml和s2t.json等文件，但是没用，出来的还是简体，咋整呢，请大佬指点指点。

**Comment by bosconb** [comment]
还有一个问题，我用了最新版的rime-wubi86-jidian方案（全盘复制粘贴包括default.custom.yaml等文件），但是发现#键无论半角还是全角固定输出都是£，切换到清歌五笔正常输出，重装rime或者修改default.custom.yaml文件的punctuator都无效果。只有我一个人有这个问题吗？

**Comment by KyleBing** [comment]
简入繁出已经更新上了， `ctrl + 0` 切换输入方案到 `简入繁出` 即可，试试能不能用。

**Comment by KyleBing** [comment]
关于 按 `#` 出 `£` 的问题好像没有看到

**Comment by KyleBing** [comment]
![简入繁出例子](https://github.com/KyleBing/rime-wubi86-jidan/blob/master/imgs/rime-tradition-output.gif)

**Comment by bosconb** [comment]
谢谢大佬回复，我试了一下，`wubi86_jidian_trad.schema.yaml`里面的schema_id是不是写错了?
```json
schema:
  schema_id: wubi86_jidian
  name: "极点五笔繁体"
  version: "1.0"
```
我换成
```
schema_id: wubi86_jidian_trad
```
可以部署成功，不过简<->繁体还不能实现，我已经安装了opencc，搞不清楚是什么原因，找个时间再排查排查。

**Comment by bosconb** [comment]
```
ln -s /Library/Input\ Methods/Squirrel.app/Contents/SharedSupport/opencc/* ~/Library/Rime/opencc/
```
還是opencc的問題，已經搞定了，多謝！

**Comment by KyleBing** [comment]
对，发现我 id 是写错了，怪不得繁体方案名字在菜单中一直显示不对。
