### ISSUE TITLE
能否增加五笔手工增删词组方案

### ISSUE THREAD

**Issue by redleafnew** [KyleBing/rime-wubi86-jidian#121]
这个有用lua实现的方法，可以实现按

一 包含以下功能

> 
> 手工造词、删词、置顶候选（dict_proc + dict_filter）
> 可以手工添加2-7字词组（不能带非汉字符号）
> 可以删除系统自带词组，但不能删除单字
> 可以置顶单字或词组，之前的首选词会变成次选
> 操作实时生效，无须重新部署
> 增删记录自动保存在新文件，后台不会修改系统原有固定词库
> 候选只显示单字开关（需要自行增加option: single_char控制）
> 候选字符集，只显示GB2312简体（6700字）或GBK全集（含繁体、生僻约2万字）
> 　（通过默认option: extended_charset控制）
> wubi86自带字表有将近8万字，有做裁减
> 调整候选顺序，单字=>二字=>三字以上（sort_filter，默认开启）
> 控制显示的候选字数量（count_filter，不需要可自行删除）

https://github.com/hchunhui/librime-lua/issues/182

但本项目没有了rime.lua，且将lua放入到了lua文件夹，

我不知道如何整个进去。

**Comment by WhisperWindE** [comment]
这个我懂, 但一时说不清楚.可以Q我50786729

**Comment by redleafnew** [comment]
加你Q了，谢谢。

**Comment by redleafnew** [comment]
https://github.com/boomker/rime-fast-xhup  这个方案也有类似功能，希望移植过来。
