### ISSUE TITLE
候选框和中英文切换时的提示图标会把已输入的字符遮盖，能不能往下点，调哪里啊，看文档了，里边没有

### ISSUE THREAD

**Issue by Dreamray** [KyleBing/rime-wubi86-jidian#122]
谢谢

**Comment by KyleBing** [comment]
不存在该问题

![2024-03-02 15 05 34](https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/e8c0771e-675c-49be-9e6f-c13b74bf6141)

**Comment by Dreamray** [comment]
在我系统上存在此问题：
系统：win10 企业版LTSC 1809 (内部版本 17763.316)
小狼毫：0.15.0，界面风格选 玫红/MacRoseo

![1](https://github.com/KyleBing/rime-wubi86-jidian/assets/9279994/1c9407a5-e8b0-4c52-95b8-ebec969a7baa)
![2](https://github.com/KyleBing/rime-wubi86-jidian/assets/9279994/98f1b413-0839-4941-9c34-61dd181d5bf5)
![3](https://github.com/KyleBing/rime-wubi86-jidian/assets/9279994/da469080-82f7-4d0a-b818-89255adda098)

系统打了如下补丁：
![4](https://github.com/KyleBing/rime-wubi86-jidian/assets/9279994/e488bd3f-934e-4dcd-900d-20a0cb3ca25d)

**Comment by KyleBing** [comment]
![2024-03-04 10 21 59](https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/161f5a09-2e2c-45ba-9593-924ff35f29e2)

把配置文件重新下一遍试试，我的 Windows 10  没问题。

**Comment by Dreamray** [comment]
试了不管用，貌似不同程序窗口表现不一样，文本编辑器sublime text没有问题，chrome、微信、系统设置里都会遮住，而且貌似微信遮住的更多，如图：
![5](https://github.com/KyleBing/rime-wubi86-jidian/assets/9279994/15c1f9ad-96d9-4889-89b3-b637eaa96489)

**Comment by bczhc** [comment]
试试默认的配置，比如朙月拼音呢。会不会是前端小狼毫的问题

**Comment by KyleBing** [comment]
确实存在这个问题： 
![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/55b1d51e-55fd-433b-9aa1-260e8dbfb8e2)

**Comment by KyleBing** [comment]
https://github.com/KyleBing/rime-wubi86-jidian/commit/8689d8cb8bd41c8b84369e59d6d0824cca730c86

小狼毫 v0.1.60 后的版本添加了字段，可以设置 `show_notifications_time` 这个提示标识的显示时长，单位为 ms，目前设置成了 200ms。
> 小狼毫 v0.1.60 版本更新说明：[https://github.com/rime/weasel/releases/tag/0.16.0
](https://github.com/rime/weasel/releases/tag/0.16.0
)

在此位置添加这一行即可：

![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/e954e1cb-2c8c-4d50-9a09-5f3c115bac54)
