### ISSUE TITLE
debian上把候选字(词)调成横向显示不起作用？

### ISSUE THREAD

**Issue by eko5624** [KyleBing/rime-wubi86-jidian#124]
修改weasel.custom.yaml中的`horizontal: true`不起作用。

**Comment by eko5624** [comment]
好的，明白了，谢谢回复。

**Comment by bczhc** [comment]
Linux上在Rime前端里配置。比如fcitx5，就在Fcitx5-configtool里面Addons -> UI -> Classic User Interface -> Vertical Candidate List。

**Comment by netcore-jroger** [comment]
Ubuntu 24.04 系统修改 `~/.config/ibus/rime/build` 目录下的 `ibus_rime.yaml` 文件，重新部署，可以实现横向显示候选词。
```yaml
...
style:
  ...
  horizontal: true
```

build 目录好像是自动生成的，所以得先把 rime 输入法正常用起来。然后再来找这个文件修改。
@KyleBing
