### ISSUE TITLE
想把原来的词库换成自己的词库，发现换不了，不管是空格还是TAB的分隔符，都是不行的

### ISSUE THREAD

**Issue by imyangdy** [KyleBing/rime-wubi86-jidian#13]
想把原来的词库换成自己的词库，发现换不了，不管是空格还是TAB的分隔符，都是不行的
工 a 
期 a 
式 aa 
戒 aa 
芽 aa 
工 aaa 
工 aaaa 
㠭 aaaa 
㐂 aaab 
菚 aaar 
工薪 aaau

**Comment by KyleBing** [comment]
查看错误日志：

```bash
# 进入放日志的文件夹
cd $TEMPDIR

# 实时查看输入法错误日志
tail -f rime.squirrel.ERROR
```

根据错误日志排查错误

<img width="1186" alt="Screen Shot 2019-11-14 at 09 17 46" src="https://user-images.githubusercontent.com/12215982/68818435-eb095900-06bf-11ea-9c40-0b9c43dee14e.png">
