### ISSUE TITLE
鼠须管1.0.1皮肤失效了　　

### ISSUE THREAD

**Issue by mykonica** [KyleBing/rime-wubi86-jidian#131]
配置已经更新到最新版本了，还是不行。
<img width="260" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/587572c1-a195-4477-a24d-6d7533f7ca7e">
<img width="383" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/ed65f4ca-8494-464a-aaaa-52d2281722c5">

<img width="742" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/0c72ded4-6157-4e22-91a8-d771f5940c82">

**Comment by KyleBing** [comment]
<img width="657" alt="Screenshot 2024-06-02 at 22 21 08" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/68f3e49b-b15c-49bb-b9d3-c7ee851d98c2">

我的显示正常，你是什么系统。

**Comment by baober90** [comment]
> 配置已经更新到最新版本了，还是不行。 <img alt="image" width="260" src="https://private-user-images.githubusercontent.com/7487435/335873850-587572c1-a195-4477-a24d-6d7533f7ca7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzkwMjUsIm5iZiI6MTcxNzM3ODcyNSwicGF0aCI6Ii83NDg3NDM1LzMzNTg3Mzg1MC01ODc1NzJjMS1hMTk1LTQ0NzctYTI0ZC02ZDc1MzNmN2NhN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDEzODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTZjZGExZTAwMTE5NzIzY2E2ZmRmOWYwMGEwY2NkZTUyMmQxMzZlZTcyMThlYjZhMTBmMGQyZTBiYWYxNzAwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L4tmHL9qwQ-GIgmq4Hp31-ZavTWwFEpu08U0BTLF_Qg"> <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/7487435/335873913-ed65f4ca-8494-464a-aaaa-52d2281722c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzkwMjUsIm5iZiI6MTcxNzM3ODcyNSwicGF0aCI6Ii83NDg3NDM1LzMzNTg3MzkxMy1lZDY1ZjRjYS04NDk0LTQ2NGEtYWFhYS01MmQyMjgxNzIyYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDEzODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdkNmZhZTRlYzk2YmQ1YzgxYjFhYmNmMjQ0YTI0MjE2MTA0YjU4YWRjM2VhMzVlMDE5ZjdmOTdhZjAyNGVhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-_b8s_3ySrGvYaA0989wBB9fqbfuPBZzA8-YVTILJTo">
> 
> <img alt="image" width="742" src="https://private-user-images.githubusercontent.com/7487435/335874038-0c72ded4-6157-4e22-91a8-d771f5940c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzkwMjUsIm5iZiI6MTcxNzM3ODcyNSwicGF0aCI6Ii83NDg3NDM1LzMzNTg3NDAzOC0wYzcyZGVkNC02MTU3LTRlMjItOTFhOC1kNzcxZjU5NDBjODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDEzODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzM4ZDBmN2NhMzZjZjg5MGZiNGVlZmE2ODY5ZTQyNzk2OGJjYjM3YzFkYWM2MjJmYmQxMzBmYzE4ZWJmNDk4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1Q6_3g6qc5fA2kDH14-LTeTwL8GGPfgYHuPaZoFp5yU">

这个解决了吗?

**Comment by mykonica** [comment]
> <img alt="Screenshot 2024-06-02 at 22 21 08" width="657" src="https://private-user-images.githubusercontent.com/12215982/335874272-68f3e49b-b15c-49bb-b9d3-c7ee851d98c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzk1NTMsIm5iZiI6MTcxNzM3OTI1MywicGF0aCI6Ii8xMjIxNTk4Mi8zMzU4NzQyNzItNjhmM2U0OWItYjE1Yy00OWJiLWI5ZDMtYzdlZTg1MWQ5OGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAxNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZTYyZDViZTk1ZGYzN2MxMmIwM2U0YWE1NWZhMDdjOGQ1MmM1ZjNiOWEwMDY4M2RjM2E0ZWJlZGYxM2FlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NWmZJVB_OSVtVv-SIPaus18YXiqRgFcQ71ZvhpIumwU">
> 我的显示正常，你是什么系统。

<img width="280" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/b763869f-56d5-404d-9368-c4423e38b11f">

**Comment by mykonica** [comment]
> <img alt="Screenshot 2024-06-02 at 22 21 08" width="657" src="https://private-user-images.githubusercontent.com/12215982/335874272-68f3e49b-b15c-49bb-b9d3-c7ee851d98c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNzk1NTMsIm5iZiI6MTcxNzM3OTI1MywicGF0aCI6Ii8xMjIxNTk4Mi8zMzU4NzQyNzItNjhmM2U0OWItYjE1Yy00OWJiLWI5ZDMtYzdlZTg1MWQ5OGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAxNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZTYyZDViZTk1ZGYzN2MxMmIwM2U0YWE1NWZhMDdjOGQ1MmM1ZjNiOWEwMDY4M2RjM2E0ZWJlZGYxM2FlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NWmZJVB_OSVtVv-SIPaus18YXiqRgFcQ71ZvhpIumwU">
> 我的显示正常，你是什么系统。

<img width="280" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/fbb469e8-9519-4a53-b61b-d3319b7b6988">

**Comment by KyleBing** [comment]
完全替换这个文件了吗，完全替换试试
https://github.com/KyleBing/rime-wubi86-jidian/blob/master/squirrel.custom.yaml

**Comment by mykonica** [comment]
> 完全替换这个文件了吗，完全替换试试 https://github.com/KyleBing/rime-wubi86-jidian/blob/master/squirrel.custom.yaml

我是完全替换的。并且有执行“重新部署”

**Comment by baober90** [comment]
> 完全替换这个文件了吗，完全替换试试 https://github.com/KyleBing/rime-wubi86-jidian/blob/master/squirrel.custom.yaml

我这边的系统版本也是: Sonoma 14.5,完全替换squirrel.custom.yaml文件的内容, 还是竖排

**Comment by bbenchen** [comment]
@KyleBing 我也是同样的问题，系统也是 Sonoma 14.5

**Comment by KyleBing** [comment]
等晚上回家看看，昨晚试着我的是可以正常显示的。

**Comment by KyleBing** [comment]
找到原因了，是因为暗黑模式时会匹配到另一个不存在的皮肤配置。  
目前已经添加了一个暗黑模式的皮肤。

```yaml
patch:
  style:
    color_scheme: roseo_maple            # 白亮模式下启用的皮肤，名字对应下方对皮肤的字义名
    color_scheme_dark: roseo_maple_dark  # 暗黑模式下启用的皮肤
```

<img width="654" alt="Screenshot 2024-06-03 at 21 32 15" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/538161d7-653a-4fb8-b7a8-8a4073e913c7">
<img width="678" alt="Screenshot 2024-06-03 at 21 31 55" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/12215982/3c67ad09-a872-4783-9d7b-330bd4d92885">


更新一下最新的 squirrel.custom.yaml 文件就可以了。

**Comment by mykonica** [comment]
可以了。多谢
<img width="515" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/c27a7153-e13e-4f72-8479-beebcb358108">

**Comment by KyleBing** [comment]
> 可以了。多谢 <img alt="image" width="515" src="https://private-user-images.githubusercontent.com/7487435/336275272-c27a7153-e13e-4f72-8479-beebcb358108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjU4MDEsIm5iZiI6MTcxNzQ2NTUwMSwicGF0aCI6Ii83NDg3NDM1LzMzNjI3NTI3Mi1jMjdhNzE1My1lMTNlLTRmNzItODQ3OS1iZWViY2IzNTgxMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMDE0NTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgzMzFhZDQwZjk0NmMxMjAyYTJhYWMyYzQ3NTIyODUyODJhYzdlNzI0ZjRkODUxNTM5NTIxOGI2OTA4MzQ1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tPsV762Xgu46h1M8OclvrppUBfP1kYiJzHjk2Zk9pVg">

如果感觉不习惯，也可以保留亮色模式下的主题，只需要修改对应的名字就可以了：

```yaml
    color_scheme: roseo_maple            # 白亮模式下启用的皮肤，名字对应下方对皮肤的字义名
    color_scheme_dark: roseo_maple_dark  # 暗黑模式下启用的皮肤
```

**Comment by bbenchen** [comment]
@KyleBing 辛苦了，谢谢。
