### ISSUE TITLE
五笔编码方案，想在侯选词后边显示拼音编码，请问该怎么配置

### ISSUE THREAD

**Issue by mykonica** [KyleBing/rime-wubi86-jidian#134]
五笔拼音方案可以在侯选词后边显示五笔编码。我用纯五笔方案时想在侯选词后显示拼音编码，请问该怎么配置？
<img width="425" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/7487435/fb24a26a-297e-4b07-bece-6467c103ed02">

**Comment by linzianxyz** [comment]
![IMG_20240705_142249](https://github.com/KyleBing/rime-wubi86-jidian/assets/15376679/1e675f3b-cee4-43d9-b6c7-aac9484206be)
是这样的吗？

**Comment by mykonica** [comment]
> ![IMG_20240705_142249](https://private-user-images.githubusercontent.com/15376679/346025499-1e675f3b-cee4-43d9-b6c7-aac9484206be.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg2MTksIm5iZiI6MTcyMDQyODMxOSwicGF0aCI6Ii8xNTM3NjY3OS8zNDYwMjU0OTktMWU2NzVmM2ItY2VlNC00M2Q5LWI2YzctYWFjOTQ4NDIwNmJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4NDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWZmMWQ3OTFjYWI3MjVkYjIwYzFkODRlOTQ5YTJlMTlmZjkyYTY0NzVlNjU1MDVmY2U1YWVjZjg5YWY1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ge2mod7FsrZvxLmu9hocrHfIfb07edaRWtM9QhMkits) 是这样的吗？

是的。请问怎么配置？

**Comment by linzianxyz** [comment]
据我所知，如果想显示拼音、自造词、反查，三者同时生效，就有问题；
 在filters添加
- "reverse_lookup_filter@pinyin_lookup"
 然后
pinyin_lookup:                          #知音查形
  tags: pinyin_lookup                                #关联标记反查
  dictionary: luna_pinyin               #翻译器将调取此字典文件
  overwrite_comment: true               # 覆蓋其他提示
  preedit_format:                       #上屏码自定义
    - xform/([nl])v/$1ü/                #拼音状态下输入nv实际显示nü
    - xform/([nl])ue/$1üe/              #n或者l后面紧跟着输入ue显示üe
    - xform/([jqxy])v/$1u/              #jqxy后面紧跟着输入v实际显示u
