### ISSUE TITLE
词库中有两个【没事】

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [KyleBing/rime-wubi86-jidian#135]
imgk 下，有三个词：【没事】【没事】【洞】。其中两个没事有不同的优先级。

![image](https://github.com/KyleBing/rime-wubi86-jidian/assets/22313057/a6b05cf3-7b66-48ab-8792-dde04beefe38)

如果这不是本义，可以改一下。

**Comment by KyleBing** [comment]
谢指正： https://github.com/KyleBing/rime-wubi86-jidian/commit/6be59178961251da527de7a69bb9ddaa6cd63c47
