### ISSUE TITLE
请求添加词库以及一些建议

### ISSUE THREAD

**Issue by XiaoTeemo** [KyleBing/rime-wubi86-jidian#14]
重置	tglf

默認配置下（XX 自動上屏），輸入網址時不太方便。

**Comment by KyleBing** [comment]
输入英文应该切换到英文状态

**Comment by XiaoTeemo** [comment]
百度輸入法是能直接輸入網址的 . 中英文標點符號混合輸入時很舒服.它需要切換的情況不多.

**Comment by XiaoTeemo** [comment]
@KyleBing 繁体下没有 “群” 这个字，要怎么加上呢？

**Comment by KyleBing** [comment]
`羣` 不知道是不是 `群` 的繁体呢？本输入方案中的繁体输出是通过程序转换而得出的。
繁体输出时，打出的字还是简体，如果该简体字有对应的繁体字，就会输出该字的繁体，如果没有就照原样输出
繁体是通过 `OpenCC `转换的。

**Comment by XiaoTeemo** [comment]
现在下载的 QQ 五笔竟然还可以导出系统词库，用深蓝转换了下，效果不错，推荐您使用。

**Comment by XiaoTeemo** [comment]
为什么我修改了 weasel.custom.yaml 和 squirrel.custom.yaml 的皮肤，重新部署后没有生效呢？

**Comment by wjinxing** [comment]
> 现在下载的 QQ 五笔竟然还可以导出系统词库，用深蓝转换了下，效果不错，推荐您使用。

请问一下如何将使用深蓝转换后的词库更换到鼠须管输入法中？

**Comment by XiaoTeemo** [comment]
@wjinxing 替换掉 wubi86_jidian.dict.yaml 里的内容就可以了

**Comment by wjinxing** [comment]
> @wjinxing 替换掉 wubi86_jidian.dict.yaml 里的内容就可以了

你的QQ五笔词库能否共享一下？传个网盘什么的，如果你没有的话我可以提供。

**Comment by XiaoTeemo** [comment]
> > @wjinxing 替换掉 wubi86_jidian.dict.yaml 里的内容就可以了
> 
> 你的QQ五笔词库能否共享一下？传个网盘什么的，如果你没有的话我可以提供。

https://file.io/shFppf

**Comment by wjinxing** [comment]
> > > @wjinxing 替换掉 wubi86_jidian.dict.yaml 里的内容就可以了
> > 
> > 
> > 你的QQ五笔词库能否共享一下？传个网盘什么的，如果你没有的话我可以提供。
> 
> https://file.io/shFppf

哥们儿，你提供的这个网盘下载地址无法访问，打开是404.要不麻烦你再重新检查一下地址，谢谢。

**Comment by XiaoTeemo** [comment]
这个词库还是少了点，很多打不出来，作者不要打我。我现在用 https://github.com/scomper/Rime 了，只要稍微改一下，加上自定义词库，好用许多了，基本达到百度五笔的水平。

**Comment by wjinxing** [comment]
> @junhuihuang
> 这个词库还是少了点，很多打不出来，作者不要打我。我现在用 https://github.com/scomper/Rime 了，只要稍微改一下，加上自定义词库，好用许多了，基本达到百度五笔的水平。

哥们儿，提供一下自定义词库呗。你上面发的那个网盘下载地址无法打开，都是404

**Comment by XiaoTeemo** [comment]
> > @junhuihuang
> > 这个词库还是少了点，很多打不出来，作者不要打我。我现在用 https://github.com/scomper/Rime 了，只要稍微改一下，加上自定义词库，好用许多了，基本达到百度五笔的水平。
> 
> 哥们儿，提供一下自定义词库呗。你上面发的那个网盘下载地址无法打开，都是404

https://github.com/scomper/Rime 这个的词库更好。

**Comment by wjinxing** [comment]
> > > @junhuihuang
> > > 这个词库还是少了点，很多打不出来，作者不要打我。我现在用 https://github.com/scomper/Rime 了，只要稍微改一下，加上自定义词库，好用许多了，基本达到百度五笔的水平。
> > 
> > 
> > 哥们儿，提供一下自定义词库呗。你上面发的那个网盘下载地址无法打开，都是404
> 
> https://github.com/scomper/Rime 这个的词库更好。

提供一下你用深蓝转换的自定义词库呗。我看你发的这个Rime了，已经做了调整和配置。但是没有你所说的自定义五笔词库。

**Comment by XiaoTeemo** [comment]
> > > > @junhuihuang
> > > > 这个词库还是少了点，很多打不出来，作者不要打我。我现在用 https://github.com/scomper/Rime 了，只要稍微改一下，加上自定义词库，好用许多了，基本达到百度五笔的水平。
> > > 
> > > 
> > > 哥们儿，提供一下自定义词库呗。你上面发的那个网盘下载地址无法打开，都是404
> > 
> > 
> > https://github.com/scomper/Rime 这个的词库更好。
> 
> 提供一下你用深蓝转换的自定义词库呗。我看你发的这个Rime了，已经做了调整和配置。但是没有你所说的自定义五笔词库。

用了他的，就没必要用深蓝转换的自定义词库，他的词库更全，还有打不出来的字，加到自定义词库的那个文件就 OK 了。

**Comment by wjinxing** [comment]
> > > > > @junhuihuang
> > > > > 这个词库还是少了点，很多打不出来，作者不要打我。我现在用 https://github.com/scomper/Rime 了，只要稍微改一下，加上自定义词库，好用许多了，基本达到百度五笔的水平。
> > > > 
> > > > 
> > > > 哥们儿，提供一下自定义词库呗。你上面发的那个网盘下载地址无法打开，都是404
> > > 
> > > 
> > > https://github.com/scomper/Rime 这个的词库更好。
> > 
> > 
> > 提供一下你用深蓝转换的自定义词库呗。我看你发的这个Rime了，已经做了调整和配置。但是没有你所说的自定义五笔词库。
> 
> 用了他的，就没必要用深蓝转换的自定义词库，他的词库更全，还有打不出来的字，加到自定义词库的那个文件就 OK 了。

试过了，确实非常OK。不过还是发现一个问题，不知道你是否存在这个问题，在MAC系统上打开任意APP，比如office或者其它软件，当修改完成之后点击另存为，在弹出的另存为对话框中输入文件名称时无法进行中英文切换。我试过好几个软件都是同样的问题。而在正常的word，excel文档中输入文字时按shift键就可以任意切换中英文。不知道你是否遇到过此问题。盼复，谢谢。

**Comment by XiaoTeemo** [comment]
我都是以英文命名，一直没发现这个问题，试了下跟你的情况一样。
