### ISSUE TITLE
Mac升级到1.02后没有提示码

### ISSUE THREAD

**Issue by xiao0yy** [KyleBing/rime-wubi86-jidian#143]
Mac Rime升级到1.02后没有提示码
![CleanShot 2024-08-04 at 22 10 34@2x](https://github.com/user-attachments/assets/2d191fd7-5269-4ad3-8a2f-2db3608f7679)

关掉配置后的效果
![CleanShot 2024-08-04 at 22 10 05@2x](https://github.com/user-attachments/assets/c5098734-dd5a-4d99-bf8b-9cbbb9818b8b)

**Comment by KyleBing** [comment]
对，就是这样。
