### ISSUE TITLE
个别字打不出来，比如 `䟀` 这个字

### ISSUE THREAD

**Issue by eko5624** [KyleBing/rime-wubi86-jidian#151]
如题，希望再扩充一下词库。

**Comment by KyleBing** [comment]
生僻字不考虑

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月21日 20:53 |
| 收件人 | KyleBing/rime-wubi86-jidian ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [KyleBing/rime-wubi86-jidian] 个别字打不出来，比如 `䟀` 这个字 (Issue #151) |

如题，希望再扩充一下词库。
