### ISSUE TITLE
请教一下如何输入大写金额

### ISSUE THREAD

**Issue by recmess** [KyleBing/rime-wubi86-jidian#17]
第一次在MAC下使用，请问如何输入大写数字，谢谢！

**Comment by KyleBing** [comment]
正常来说好像应该有专门的码表对应，目前是需要跟打字一样打出来。

**Comment by KyleBing** [comment]
已添加支持，具体可以查看 `README.md` 文件

<img title="大写数字输入案例" src="https://github.com/KyleBing/rime-wubi86-jidan/blob/master/imgs/input_number.gif" width="500">
