### ISSUE TITLE
怎麼調整候選詞的順序

### ISSUE THREAD

**Issue by bosconb** [KyleBing/rime-wubi86-jidian#18]
比如我打 `ujtm` 會跳出四個選項：
```
1、意向，2、單身，3、單向，4、贛
```
現在我想讓第二個詞「單身」上升到第一選項，在清歌五筆中，可以按 ctrl+序號快捷調整詞序，但在 rime 中，我只能在自建的`wubi86_jidian_user.dict.yaml`詞庫中，提升「單身」的詞頻，重新部署來調整詞序。

那麼我想問的是，應該在`wubi86_jidian.dict.yaml`裏修改詞頻呢，還是直接在`wubi86_jidian_user.dict.yaml`加上詞頻，如果是後者，兩個詞庫裏重複的詞語（比如上述的「單身」）會有衝突嗎？（我其實不太喜歡改動`wubi86_jidian.dict.yaml`）

**Comment by KyleBing** [comment]
调整词序是通过调整词的位置，或者添加词频来实现的，没有快捷键调整。
对于重复的字词，最好是手动定位并消除，如果确实不想手机来，可以看看这个说明文档里的 `filters` 项，里面有个 unifier 应该可以过滤重复的字词，不过没有试过。

[码表方案字段说明](https://github.com/KyleBing/rime-wubi86-jidian/blob/master/%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3/%E7%A0%81%E8%A1%A8%E6%96%B9%E6%A1%88%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E.md)

我一般是在没有这个词的时候才添加，对于不同词库的词频调整，就需要用到后面的 词频 了，手动添加。

**Comment by bosconb** [comment]
好吧，謝謝回覆！
另：wubi86_jidian.dict.yaml裏出現一條「杜志民 sfna」很奇怪，我替換成 「村民 sfna」了

**Comment by KyleBing** [comment]
嗯，确实 [村民 sfna] 这个词确实有问题，已修正。
