### ISSUE TITLE
五笔混合输入状态下使用拼音好多词都没有

### ISSUE THREAD

**Issue by wjinxing** [KyleBing/rime-wubi86-jidian#19]
直接输入xiaomishouji这样的拼音，是无法正常显示小米手机这个词语的。

**Comment by KyleBing** [comment]
因为拼音词库里没有这个词，该词库的目标是小而精，像`小米手机` 这样的词，在五笔中应该是拆分成这个词打才快。
减少特殊词的数量，增加通用词的频率。
