### ISSUE TITLE
用户如何快速自定义词（无法生效）

### ISSUE THREAD

**Issue by Fzrone** [KyleBing/rime-wubi86-jidian#23]
Rime（Mac版本）
从Github上拉下配置后，部署同步后，在wubi86_jidian_user.dict.yaml这里面自定义词，比如:`张三[\t]xtdg[\t]1 `，然后部署和同步后输入xtdg没有张三这个选项，是不是我的设置操作有问题。我使用的是vim编辑器，与vim配置（修改了tab默认长度为4个空格）有关吗？还是方法不对。这个问题已经困扰我很久了，查看了配置文件也不知道出在了哪！方便的话可远程下。

**Comment by KyleBing** [comment]
错误很明显，中间是要 tab 间隔的，你现在是空格间隔的。

`4个空格`  不等于 `tab`

你需要用 tab 间隔可以了

**Comment by Fzrone** [comment]
谢谢您的建议！
我明白了，我的配置是这样的
![Code](https://user-images.githubusercontent.com/34593288/71481422-bfd66580-2838-11ea-800f-7ed6a17c83cd.png)
我不知道什么时候把by_weight前面的#去掉了，刚刚又检查了一下，将这个选项关闭，在检查语法错误的时候就能通过了

**Comment by Fzrone** [comment]
再问个问题，如何把输入框去掉，什么都不显示，实现盲打？我觉得这个重码率已经很低了，不需要显示状态栏了。Mac提供这样的接口了吗？没有就算了

**Comment by KyleBing** [comment]
嗯，能正常布署就好。
无输入框这个。。有空看一下，感觉上应该可以吧

**Comment by KyleBing** [comment]
输入框目前好像没有去掉的方法，你自己可以探索一下。
