### ISSUE TITLE
【占位】wiki 图片存放处

### ISSUE THREAD

**Issue by KyleBing** [KyleBing/rime-wubi86-jidian#24]
> 此处用于方便存放 `wiki` 中用到的图片

`SublimeText`

![sublime-editor](https://user-images.githubusercontent.com/12215982/71498648-1d4dcf00-2898-11ea-8c74-0bc1b23813d5.png)

![sublime-export-tab](https://user-images.githubusercontent.com/12215982/71498650-20e15600-2898-11ea-91f6-b7b2f64426eb.png)

**Comment by bosconb** [comment]
现在用textmate编辑，ST总是忘了切换

**Comment by KyleBing** [comment]
> 现在用textmate编辑，ST总是忘了切换

试用了下 `textmate`， 写纯文本真的挺好用，关于 `TabSize` 设定不会在下次打开时重置。 `sublime` 就会在每次打开时重置很麻烦，不错哟。

**Comment by KyleBing** [comment]
[wubi86 scomper 版.zip](https://github.com/KyleBing/rime-wubi86-jidian/files/4509884/wubi86.scomper.zip)

[https://github.com/scomper/Rime](https://github.com/scomper/Rime)

由 `scomper` 的配置中五笔码表删减无用字符所得，但没有一级简码的二选词，像 R 键二选的 “白”，C 键 二选的 “又” 都没有，不习惯

**Comment by KyleBing** [comment]
字体设置：
![font-face](https://user-images.githubusercontent.com/12215982/81519978-8597db80-9375-11ea-910d-6fa52e870871.png)

**Comment by KyleBing** [comment]
README.md 图片

![input_number](https://user-images.githubusercontent.com/12215982/81521150-fab8e000-9378-11ea-8b38-1caf43d6fdd2.gif)
![logo](https://user-images.githubusercontent.com/12215982/81521171-01475780-9379-11ea-99b1-32ae5d3b15db.png)
![main](https://user-images.githubusercontent.com/12215982/81521174-02788480-9379-11ea-84be-b56e0b5e72c9.gif)
![rime_setup_windows_start](https://user-images.githubusercontent.com/12215982/81521177-03111b00-9379-11ea-883b-721925e30fa0.png)
![rime_skin_windows](https://user-images.githubusercontent.com/12215982/81521178-03a9b180-9379-11ea-99fc-6d5d262a20d4.png)
![rime-tradition-output](https://user-images.githubusercontent.com/12215982/81521180-04dade80-9379-11ea-9d41-fd8a58d293ab.gif)
![Rime五笔输入法](https://user-images.githubusercontent.com/12215982/81521182-05737500-9379-11ea-887f-a5eb3fbb3b65.gif)
![skin](https://user-images.githubusercontent.com/12215982/81521185-060c0b80-9379-11ea-95eb-ad755394936e.png)
<img width="177" alt="windows_skin" src="https://user-images.githubusercontent.com/12215982/81521186-073d3880-9379-11ea-953f-0fca61e82c5d.png">

**Comment by KyleBing** [comment]
Skin maple magenta
![skin_maple_magenta@2x](https://user-images.githubusercontent.com/12215982/81521502-fa6d1480-9379-11ea-9ff2-4a730131ea52.png)

**Comment by KyleBing** [comment]
![main-input-example](https://user-images.githubusercontent.com/12215982/81524061-6f444c80-9382-11ea-9ecc-edb38a2cfc3f.gif)

**Comment by KyleBing** [comment]
![Uploading Rime.png…]()

**Comment by KyleBing** [comment]
![Rime](https://user-images.githubusercontent.com/12215982/99625640-a1d6ac80-2a6b-11eb-91b0-ba55003bc3b1.png)

**Comment by KyleBing** [comment]
<img width="435" alt="Screen Shot 2020-12-09 at 12 15 57" src="https://user-images.githubusercontent.com/12215982/101584309-56833e80-3a18-11eb-9b83-a43204ad363c.png">

**Comment by KyleBing** [comment]
<img width="383" alt="auto-create-words" src="https://user-images.githubusercontent.com/12215982/114480409-1ab1ed00-9c35-11eb-84d4-44a387232ace.png">

**Comment by KyleBing** [comment]
<img width="463" alt="auto-create-words" src="https://user-images.githubusercontent.com/12215982/114480534-4b922200-9c35-11eb-8d08-4c8eacb407a2.png">

**Comment by KyleBing** [comment]
![skin-windows](https://user-images.githubusercontent.com/12215982/126967080-924f8ae4-ac81-47e2-b6c8-9f415aa6ead8.jpg)

**Comment by KyleBing** [comment]
<img width="300" alt="auto-create-words" src="https://user-images.githubusercontent.com/12215982/127078734-41584c0f-96b8-4630-8cd4-3522d9ce384e.jpg">
<img width="300" alt="auto-create-words" src="https://user-images.githubusercontent.com/12215982/127078737-9b6fb1c9-3b32-42e9-970f-baeb68c024b0.jpg">
<img width="300" alt="auto-create-words" src="https://user-images.githubusercontent.com/12215982/127078741-c4eb7b20-2199-4eea-a6da-491ff620a695.jpg">

**Comment by KyleBing** [comment]
ibus-rime skin
![input-rime](https://user-images.githubusercontent.com/12215982/131607073-0b3dfe0e-bfc8-4be0-91c7-b304702acdda.png)

**Comment by KyleBing** [comment]
符号输入：
注音
![2021-09-22 13 58 27](https://user-images.githubusercontent.com/12215982/134290996-d65fcb0a-303a-4d11-8905-840f614ca8fd.jpg)
希腊
![2021-09-22 13 58 42](https://user-images.githubusercontent.com/12215982/134291024-7df6073c-ec5a-420c-bcd1-2e63ea33d04b.jpg)
罗马
![2021-09-22 13 58 50](https://user-images.githubusercontent.com/12215982/134291050-919aca1e-4250-4328-b8d3-33e97b6af80e.jpg)
单位
![2021-09-22 13 59 02](https://user-images.githubusercontent.com/12215982/134291069-5f525041-283c-483b-acce-82c70cc3351d.jpg)

还有其它的一些不知道的

**Comment by KyleBing** [comment]
![2021-09-22 14 17 45](https://user-images.githubusercontent.com/12215982/134292562-4297480e-cc3c-4ba7-b3ce-f5f28e9b300b.jpg)
