### ISSUE TITLE
wubi86_jidian.dict.yaml original拼写错误

### ISSUE THREAD

**Issue by limingjie** [KyleBing/rime-wubi86-jidian#28]
https://github.com/KyleBing/rime-wubi86-jidian/blob/504adf0025feb2d14c5eabb8a1778e21626da7a9/wubi86_jidian.dict.yaml#L5

```
sort: original #by_weight/权重 original/原始
```

P.S. 感谢大佬的词库，我已经在Mac和iOS上全面使用了。

**Comment by KyleBing** [comment]
多谢指正
