### ISSUE TITLE
能实现用五笔反查拼音吗?

### ISSUE THREAD

**Issue by fcying** [KyleBing/rime-wubi86-jidian#29]
有些字会写不会读的.......

**Comment by KyleBing** [comment]
这种情况用百度就可以了

**Comment by fcying** [comment]
用输入法不是快点么....给pinyin_simp 加了个五笔反查...也能用...就是要切换下输入法...

**Comment by fcying** [comment]
试了下用reverse_lookup_filter代替reverse_lookup_translator, 可以同时实现. 
现在`z`开头是 拼音反查五笔, `zi` 开头是五笔反查拼音
