### ISSUE TITLE
特殊符号打法以及在idea中的bug

### ISSUE THREAD

**Issue by gaoxinlei** [KyleBing/rime-wubi86-jidian#31]
首先谢谢作者,最近碰上两个问题,一个是特殊符号怎么打,能否配置成极点五笔的"zzts"之类的方式.
另外,发现在Intellij idea中,切换成英文态后,输入英文时经常出现重复上屏,比如new 会打成www,nww,只有切换成别的输入法才能恢复正常.在之前用别的鼠须管没有碰到这种问题.
求帮助,谢谢作者.

**Comment by fcying** [comment]
这边是`cots`
改z开头可能就不好用了. ....z 开头现在是反查.

**Comment by KyleBing** [comment]
特殊符号可以用  `co` 开头打出来，具体的可以看词库里怎么写的。  也可以根据自己需要添加。
在 `JetBrains` 产品中使用英文没有发现你说的这种情况。
