### ISSUE TITLE
特殊符号可以用  `co` 开头打出来，具体的可以看词库里怎么写的。  也可以根据自己需要添加。

### ISSUE THREAD

**Issue by gaoxinlei** [KyleBing/rime-wubi86-jidian#33]
特殊符号可以用  `co` 开头打出来，具体的可以看词库里怎么写的。  也可以根据自己需要添加。
在 `JetBrains` 产品中使用英文没有发现你说的这种情况。

_Originally posted by @KyleBing in https://github.com/KyleBing/rime-wubi86-jidian/issues/31#issuecomment-591949770_

**Comment by gaoxinlei** [comment]
谢谢,特殊符号清楚了,在idea里面使用时,需要连续打,或者自己用快点的速度能复现出来,一般实际场景下常见.如果要自己复现的话,你可以不停地打new,我就尝试过,自己不停地打new,并且绝对保证n在前且三个键不重复按,经常打出nww,www,这种出现重复上屏的,但绝对不会乱序,就是new能打出www,但打不出wen.
如果有必要,我可以录个屏传上来.

**Comment by KyleBing** [comment]
没有发现这种情况，可能是你安装的插件什么的问题。

**Comment by gaoxinlei** [comment]
> 没有发现这种情况，可能是你安装的插件什么的问题。

好吧,我现在打注释就切回来,打代码就切到英文,先这么忍着吧.
