### ISSUE TITLE
大写数字方案里的元应为元，而非圆

### ISSUE THREAD

**Issue by bosconb** [KyleBing/rime-wubi86-jidian#37]
1. readme里写的`y`对应是`月圆亿`，是错的，但部署numbers.schema.yaml后，实际按`y`打出来候选是`月元亿`，是正确的。应该是发布的时候给忘了？

依据：[会计中大写数字元到底是圆还是元-会计学堂](https://www.acc5.com/news-shuiwu/detail_110932.html)

2. 根据readme按shift键应该出来的是`wqbsjfd.	万佰仟拾角分第点`，而实际出来的是`万仟佰拾角分第点`，应该也是笔误吧？

**Comment by KyleBing** [comment]
已修正

4f2e0b97b3f6b30965bc21f9d4fe881380f15646
