### ISSUE TITLE
Mac 装完后看不到部署按钮

### ISSUE THREAD

**Issue by jacdy** [KyleBing/rime-wubi86-jidian#38]
Mac 装完后看不到部署按钮，是在哪里有部署按钮呢？

**Comment by jacdy** [comment]
导入您 的文件后，按 Ctrl + ` 也没有列出五笔可以选择。

**Comment by KyleBing** [comment]
看不到布署按钮是应用程序的事，重启电脑或者退出当前用户重新登录应该就好了。
这个配置文件的快捷键是 <kbd>control + shift + 0</kbd>

如果还不行，看看文件位置是否放对了，根据 README.md 文件里的说明放置。
