### ISSUE TITLE
在开启用户词库后，系统词库的顺序也会变化。

### ISSUE THREAD

**Issue by 37976120** [KyleBing/rime-wubi86-jidian#39]
请问怎么在开启用户词库后依然固定原词库的顺序呢？

**Comment by KyleBing** [comment]
是有这问题，目前无解。

**Comment by 37976120** [comment]
呀，看来目前只有先手动编辑词库加词了。。

**Comment by KyleBing** [comment]
[https://github.com/rime/squirrel/issues/399](https://github.com/rime/squirrel/issues/399)

**Comment by KyleBing** [comment]
可以使用这个分支的文件，可以实现手动造词并不会影响原有词库词序
[https://github.com/KyleBing/rime-wubi86-jidian/tree/phrase](https://github.com/KyleBing/rime-wubi86-jidian/tree/phrase)
