### ISSUE TITLE
建议增加多翻译器来实现固定单字词频

### ISSUE THREAD

**Issue by qq420100523** [KyleBing/rime-wubi86-jidian#4]
可以参考一下这个https://github.com/yanhuacuo/98wubi?files=1

**Comment by KyleBing** [comment]
感觉极点码表中的单字位置已经很好了。五笔的单字位置最好是自己定义，并且不要随意修改，越固定越好。

这个我是没有看懂的，你可以起个 Pull Request

**Comment by 37976120** [comment]
请问在开启用户词典后词库中的顺序也会变，这个怎么解决呢？
