### ISSUE TITLE
能不能增加一下拼音的词库

### ISSUE THREAD

**Issue by hgaoping** [KyleBing/rime-wubi86-jidian#41]
比如说像土豪，用拼音的话是打不出来的。五笔可以。

另外，默认的字体能不能大一些，18太小了，最少也的28以上，要不然字体太小。不过我认为默认的那个样式最漂亮

**Comment by hgaoping** [comment]
五笔词库还是偏少，比如说打安卓也是打不出来，有办法导入sogou不

**Comment by KyleBing** [comment]
是，词库里的词太少，有 txt 版的就可以转。

**Comment by hgaoping** [comment]
这种可以直接一并打包进去吗，很少有人会去弄这个。目前RIME输入法五笔做的最好就你这个了

**Comment by KyleBing** [comment]
你有txt可以发给我，我看看，正在考虑是不是改成词汇比较丰富的词库，极点词库对日常使用来说，实在是有点太少了

**Comment by hgaoping** [comment]
这个我也没有，网上好像有那种工具可以把搜狗的导出来

**Comment by hgaoping** [comment]
你那个添加词库的软件有没有已经编译好的可以直接下载

**Comment by KyleBing** [comment]
在release 里
