### ISSUE TITLE
想输入共，会出现Apple Watch

### ISSUE THREAD

**Issue by hgaoping** [KyleBing/rime-wubi86-jidian#42]
还有就是词库感觉还是有点少，有办法用搜狗的词库吗

**Comment by KyleBing** [comment]
是，`Apple Watch` 已经删除了。
是，词库里的词是过少了点，关于搜狗词库，目前没有词库 `txt` 文件，如果你有的话可以分享下，我给参考着加到原有词库中。

**Comment by hgaoping** [comment]
你那个添加词库的工具能安装了，这样发现也能解决不少问题。输入 法自带的提示文字大小能不能默认大一点，界面风格能不能和拼音一样，感觉他默认的那个提示界面比较好看

**Comment by hgaoping** [comment]
他默认的拼音输入法的文字大小也比较大啊

**Comment by KyleBing** [comment]
输入框字体大小可以自定义，编辑文件 `squirrel.custom.yaml` 


<img width="618" alt="Screen Shot 2020-05-11 at 11 30 24" src="https://user-images.githubusercontent.com/12215982/81525240-a288da80-9386-11ea-8f80-1396fcb11281.png">
