### ISSUE TITLE
请问为什么一个词在wubi86_jidian.dict添加能行，在wubi86_jidian_addition.dict就不行呢？

### ISSUE THREAD

**Issue by vvyoko** [KyleBing/rime-wubi86-jidian#44]
白起	rrfh
韩信	fjwy
初音	puuj

以上三个在wubi86_jidian_addition.dict中无论怎么添加都不行
无论是添加到哪个位置，还是重新手动删掉添加还是直接复制过来都不行。

直接复制放到wubi86_jidian.dict中任意一个位置又行了，这是什么原因？

其他的词都能正常添加，比方下面的
初音未来	pufg

系统windows10 1909
程序和配置全是当前最新的。

**Comment by vvyoko** [comment]
看了下说明
用户词库应该是添加到wubi86_jidian_user.dict

但是还是同样的问题，添加到这不行，只能添加到wubi86_jidian.dict

**Comment by fcying** [comment]
测试没问题, 你是不是 词和码 中间是空格 不是tab键

**Comment by KyleBing** [comment]
![image](https://user-images.githubusercontent.com/12215982/86813950-5a024a80-c0b3-11ea-982c-60b3c4846b46.png)

同样测试没问题，编码与词之间的间隔不是空格，是 `tab`，你需要找一个可以显示隐藏编码的文本编辑器，如： sublimeText
如上图，最后一条中间是空格，不会生效，其它中间是 `tab`，正常生效。

**Comment by vvyoko** [comment]
奇怪了，今天重新打开电脑什么也没干就正常了。

**Comment by KyleBing** [comment]
可能是之前没点击 布署？

**Comment by vvyoko** [comment]
> 可能是之前没点击 布署？

点了，不然怎么会有的正常有的不正常呢。
我是一次性添加一堆，然后布署后再依次单个输入测试找出这三个不行的。
复制到其他dict行就某个不行我才会疑问的，不是tab的原因。

刚完整测试了一下，我先备份wubi86_jidian_user.dict.yaml，然后清空了rime的用户文件夹，重新下载本配置，再还原wubi86_jidian_user.dict.yaml，再点布署。又是一样的问题，真是奇了怪了。

输入情况
![1](https://user-images.githubusercontent.com/2145741/86885165-62946880-c127-11ea-920b-e047b07640c3.gif)

词库截图
![1](https://user-images.githubusercontent.com/2145741/86885188-688a4980-c127-11ea-8ecc-0efff324837d.jpg)

wubi86_jidian_user.dict.yaml文件。
[wubi86_jidian_user.dict.zip](https://github.com/KyleBing/rime-wubi86-jidian/files/4888898/wubi86_jidian_user.dict.zip)

**Comment by vvyoko** [comment]
搞半天我找到原因了。。。太乌龙了
原来默认只有三个候选，这三个都是在后面的。。。。
wubi86_jidian.dict 可能权重高一些所以能显示出来。

rime 候选词有换页吗，常用的 pgdn ，= 都不行。

可以自定义 wubi86_jidian_user.dict 的权重吗
sort: original 改为 by_weight 再在每个词后面添加 1 吗？
有点太麻烦了，有地方可以定义让 wubi86_jidian_user.dict 比 wubi86_jidian.dict 的整体权重高一些吗
