### ISSUE TITLE
输入date时，并未输出系统时间

### ISSUE THREAD

**Issue by bylucky** [KyleBing/rime-wubi86-jidian#47]
请教，我尝试在全角、半角、中文、英文的状态下都未输出系统时间，是还需要单独配置某个文件吗？

**Comment by KyleBing** [comment]
不需要单独配置某个文件。什么系统呀 macOS ？  Windows？

**Comment by bylucky** [comment]
macOS，输入date 后 什么也没显示

**Comment by bylucky** [comment]
我今天重新安装后就正常了，感谢
