### ISSUE TITLE
4码候选唯一时自动上屏的选项在哪里设置

### ISSUE THREAD

**Issue by sh0w1ov3** [KyleBing/rime-wubi86-jidian#50]
前几日同步了您最新的库，发现这个4码唯一自动上屏的功能没了，必须敲第五下空格才可以稳稳的输入。
请问这个在哪里可以设置自动上屏。

**Comment by KyleBing** [comment]
目前就是四码唯一时自动上屏的  [wubi86_jidian.schema.yaml](https://github.com/KyleBing/rime-wubi86-jidian/blob/master/wubi86_jidian.schema.yaml)

**Comment by sh0w1ov3** [comment]
您好，这是我下载的最新的版本，解压后我运行了自动复制的脚本command，完成后执行重新部署，确认了版本0.14.0
我在这里打字一样还是没有4码上屏的功能，必须按第五下空格。难道是我的macOS问题吗？10.12.6
[rime-wubi86-jidian-master.zip](https://github.com/KyleBing/rime-wubi86-jidian/files/5616053/rime-wubi86-jidian-master.zip)

**Comment by KyleBing** [comment]
四码唯一时才会自动上屏，不唯一时只会字上屏。

**Comment by sh0w1ov3** [comment]
您好，我没有找到您预留的qq，我也不太会截gif

**Comment by sh0w1ov3** [comment]
gif截图好了
![iShot2020-11-30 22 57 36](https://user-images.githubusercontent.com/33852403/100625549-a3ec1580-335f-11eb-9043-ba4de6d70d79.gif)

**Comment by KyleBing** [comment]
怎么说呢，我的是可以自动上屏的。

**Comment by KyleBing** [comment]
另外，如果同步最新库内文件的话，打字的时候应该是没有编码提示的。你可以完全替换掉所有的配置文件试试。

**Comment by sh0w1ov3** [comment]
您这个gif咋弄的好清晰

**Comment by KyleBing** [comment]
用 [Gif Brewery](https://apps.apple.com/cn/app/gif-brewery-3-by-gfycat/id1081413713?l=en&mt=12) App Store 就有，免费不免费就忘了。

**Comment by qiumzh** [comment]
重新覆盖更新就可以啦
