### ISSUE TITLE
怎样开启自动造词

### ISSUE THREAD

**Issue by szylmzs** [KyleBing/rime-wubi86-jidian#57]
词组旁边有个太极的符号，是用户多次输入的，会自动添加到词库里，这个功能怎么开启

**Comment by KyleBing** [comment]
### 5. 开启自动造词

<img width="463" alt="auto-create-words" src="https://user-images.githubusercontent.com/12215982/114480534-4b922200-9c35-11eb-8d08-4c8eacb407a2.png">

__注意__: 这样会关闭自动上屏，顶字上屏的功能。

需要修改下面几个内容

```bash
speller:
  # max_code_length: 4                 # 四码上屏
  auto_select: false                   # 自动上屏

translator:
  enable_sentence: true                # 句子输入模式
  enable_user_dict: true               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: true

```
