### ISSUE TITLE
wubi86_jidian_user.schema.yaml 在目录中并不存在

### ISSUE THREAD

**Issue by euii** [KyleBing/rime-wubi86-jidian#6]
我想增加一些自造词，但是按说明并没有找到`wubi86_jidian_user.schema.yaml`这个文件，
但是发现了`wubi86_jidian_user.dict.yaml` 这个文件，我在这个文件中增加了一些自造词，然后重新点击deploy 和 sync user data ，但是都没有用，不知道问题何在？请指教。

**Comment by euii** [comment]
sorry，是我本人的问题，vim里直接把tab变成空格了，但是readme里的说明错误这个问题还是存在的。

**Comment by KyleBing** [comment]
嗯嗯，说明确实有问题
