### ISSUE TITLE
如何配置实现回车键输出字母

### ISSUE THREAD

**Issue by zinwalin** [KyleBing/rime-wubi86-jidian#69]
现在是按shift键先切换到ABC模式，不是很方便。  有没有办法可以按回车键直接输出输入的字母？

这个项目非常棒。

**Comment by KyleBing** [comment]
### 1. 回车清码
默认是开启的
打开 `default.custom.yaml` 文件，找到下面这行，在前面添加 `#` 即可

```yaml
      # 回车清码
      - { when: composing, accept: Return, send: Escape }
```
