### ISSUE TITLE
Macbook pro 2018 使用“中/英”键切换“ABC”输入模式无效

### ISSUE THREAD

**Issue by loaden** [KyleBing/rime-wubi86-jidian#7]
已经习惯了macOS系统默认输入法的Caps-lock键实现中英文切换了。请问如何让这个功能有效呢？  就像内置输入法一样。我查了很久资料，都没有找到这个解决方案。

**Comment by KyleBing** [comment]
确实是个有趣的问题，之前没注意过，刚查了下资料，找到了相关的设置选项。
现在已经加上了，目前的输入方案是可以用 cap 和 shift 切换中英文。
如果想自行设置，可以打开 `default.custom.yaml` 这个文件修改，里面已有说明

刚刚测试发现：在 phpstorm 中无法正常使用，按 `cap` 还是会切到大写，所以保留了 shift 切换中英文的功能。

**Comment by loaden** [comment]
非常感谢你的积极跟进与完善，但目前的解决方案还不完美：仅仅实现了CapsLock键实现在RIME输入法自身中英文切换（状态栏图标没有变化，说明没有实现输入法切换），而且目前的方案会导致大写键虽然亮灯，却不能输入大写。此时要输入大写，只能按住Shift键来实现了。
Macbook Pro扩展了CapsLock功能键，实现短按会在当前中文输入法和英文ABC输入法之间切换，短按后状态栏的图标也会在“A”和当前输入法图标之间变换。短按时，CapsLock键上的绿灯不亮，长按CAPS后（大约1秒）会自动切换到英文大写，此时CapsLock键的绿灯会亮起，再短按一次CAPS，还会切换回之前选择的中文输入法从而继续输入中文。

**Comment by KyleBing** [comment]
切换输入法是肯定不可能的呀，因为是在输入法内部。
如果是点cap输入大写的英文，默认就是这样的，不需要切换中英文的。

**Comment by loaden** [comment]
但mac系统自带的“简体拼音”和“五笔型”输入法，却可以通过短按CapsLock来实现与“ABC”英文输入法的切换。
此外，还有个clear状态，你注释里没提到，例如我可以这样：
```  ascii_composer:
    good_old_caps_lock: true   # true: 在保持 cap 键原有的特征， false: 点击不会切换大小写
    switch_key:
      Caps_Lock: clear```
