### ISSUE TITLE
拼音输入状态下如何去掉候选生僻字？

### ISSUE THREAD

**Issue by f2sky** [KyleBing/rime-wubi86-jidian#72]
前提：不会五笔，仅使用简体拼音输入。
在简体拼音输入状态下的情况。

1、去掉大量出现的“呒”生僻字
例如想输入“**项目**”这个词时，打出“**xiangm**”就会出现“**想呒**”这个候选词，如何去掉“**呒**”这个大量在候选词中出现的生僻字？
<img width="311" alt="Snipaste220322115026" src="https://user-images.githubusercontent.com/8769077/159404723-fc9cb59f-46ac-4efc-90e0-3872ffc8a037.png">

2、如何直接输入“**顿号 、**”上屏
在简体拼音中文输入时，直接输入“、| \”（回车键上面的一个键位），不能直接打出“、”，而需要多一个选字操作，如何修改为直接上屏？
<img width="349" alt="Snipaste220322115109" src="https://user-images.githubusercontent.com/8769077/159405327-f6a6898d-76b7-430c-a4fd-bdb5e09ea4f5.png">

**Comment by KyleBing** [comment]
Rime 的拼音不是太智能，输入 `xiang m` 的时候它会去找 `m` 开头的单字里靠前的单字，可以手动将这些用不到的字从 `pinyin_simp.dict.yaml` 中删除。

![2022-03-22 122732](https://user-images.githubusercontent.com/12215982/159408857-99fdcc63-5711-4fb1-b326-fd842f15280d.png)



### 符号：
修改 `pinyin_simp.schema.yaml` 文件 `import_preset: default` 即可，或者更新最新的项目文件，我已经修改了。

```yaml
punctuator:
  import_preset: default
```

**Comment by f2sky** [comment]
感谢回复！
顿号直接上屏的问题已经解决了。

1、关于生僻字的问题
还是输入`xiangm`，在候选项中能出现`项`，但是`m`却不会接着出现`目`，这样自造词就无法产生了。实际上这些词是不存在的，该如何优化？例如直接导入搜狗、百度的词库能优化这个问题吗？
<img width="185" alt="34532452452" src="https://user-images.githubusercontent.com/8769077/159412957-eb69e3f8-5982-47db-9dc5-e17cacc80fb5.png">

2、拼音输入状态下，如何直接输入字母？
例如我打出`xiangmu`，按回车就清空了，如果让`xiangmu`这一串字母直接上屏，该如何设置？

**Comment by f2sky** [comment]
回车清空的问题解决了，将pinyin_simp.schema.yaml的配置文件中，这一句注释掉：
`# - { when: composing, accept: Return, send: Escape }`
