### ISSUE TITLE
ctrl + space 的禁用功能

### ISSUE THREAD

**Issue by e71828** [KyleBing/rime-wubi86-jidian#73]
大哥大姐，很感谢各位的工作与奉献。

与PyCharm的Ctrl+Space键冲突

烦请提携，在哪里可以自定义，或disable 该功能

**Comment by KyleBing** [comment]
<kbd>ctrl</kbd>+<kbd>space</kbd> 没有设备任何快捷键吧，如果冲突，可以修改 pycharm 的快捷键，【设置】 【keymaps】 修改对应的快捷键即可

**Comment by e71828** [comment]
ctrl+space 是 禁用输入法啊，大佬。
