### ISSUE TITLE
几个小Bug

### ISSUE THREAD

**Issue by ansonliao** [KyleBing/rime-wubi86-jidian#74]
1. 在简入繁出的时候，关闭四码自动上屏功能常常失效，即会自动上屏
2. 选择输入模式，使用回车键选择不生效

谢谢！

**Comment by KyleBing** [comment]
具体描述

**Comment by ansonliao** [comment]
1. 在简入繁出的时候，关闭四码自动上屏功能常常失效，即会自动上屏
    1.1 在设置文件`wubi86_jidian.schema.yaml`里面，把4码自动上屏的设置关掉，
    1.2 在简体输入模式下（即 `极点五笔86`）4码是不会上屏的
    1.3 切换输入法至 ` 简入繁出`时，输入4码字会自动上屏，比如 `嘅`（编码是：kvcq)
    1.4 `嘅` 这个字在简体输入模式下，也能打出来，关闭4码上屏功能，简体输入模式下，打`kvcq`不会自动上屏，在`简入繁出`下，打`kvcq`会自动上屏


```
speller:
#  max_code_length: 4                    # 四码上屏
  auto_select: false                     # 四码唯一时，自动上屏
#  auto_clear: max_length                # 空码时自动清空
```
2. 选择输入模式，使用回车键选择不生效
    
```
GIVEN `极点五笔86` 输入模式
WHEN 按ctrl + 0 进入输入切换模式
AND 按方向键选中 `简入繁出` 模式
AND 按 `Enter` 键
THEN 打一个中文字输入五笔编码 `p` (“这”字)，输出简体字 `这`，非繁体字 `這`
```

**Comment by KyleBing** [comment]
1. 简体和繁体是两个不同的方案文件，改这个文件就可以了 `wubi86_jidian_trad.schema.yaml`
2. 选择的选择跟输入文字是一样的，回车是取消输入，一般用<kbd>空格</kbd>确认就可以了。

**Comment by ansonliao** [comment]
Hi @KyleBing 
1. 通过修改 `wubi86_jidian_trad.schema.yaml`，已经解决繁体输入模式下四码自动上屏的情况，原来繁简体是不同配置文件的，抱歉，没仔细阅读使用文档。
2. 使用 `空格` 确实可以实现选择模式，请教记得之前的版本，使用 `enter` 也是可以选择模式的，这个更改原因是什么呢？

**Comment by KyleBing** [comment]
因为添加了 enter 清码的功能。可以搜搜说明页中 “回车” 看看，应该是这个问题。
