### ISSUE TITLE
date、time、week都会出现以下变量类型的情况，如何修正？

### ISSUE THREAD

**Issue by bevingt** [KyleBing/rime-wubi86-jidian#77]
date
<img width="573" alt="image" src="https://user-images.githubusercontent.com/33823663/176571883-5d7c3ffd-ce5e-41f0-8225-10a7087c3ae7.png">
time
<img width="585" alt="image" src="https://user-images.githubusercontent.com/33823663/176571915-a2d7e9a2-88ac-4df0-9b6a-ef820e04e722.png">
week
<img width="467" alt="image" src="https://user-images.githubusercontent.com/33823663/176571950-a156647b-eb40-4cab-96fe-1c433fce3bb0.png">

**Comment by bevingt** [comment]
不清楚哪来的，我注释掉了第三方字库，也是一样的情况。系统在win和mac上都出现了这种情况

**Comment by KyleBing** [comment]
感觉好像是词库里的，就是字符串，不是输入法生成的。你可以找到你的词库，然后搜一下这些内容，应该能搜到的。

**Comment by bevingt** [comment]
可以了，我重新下载布署就没问题了，只是奇怪，我检查了词库并没发现这些错误的词条。

**Comment by KyleBing** [comment]
我原词库里是没有这些词条的，但我知道其它词库中可能会有这些词条。嗯嗯，解决了就好。
