### ISSUE TITLE
怎么删除词库里的繁体字啊

### ISSUE THREAD

**Issue by songxing10000** [KyleBing/rime-wubi86-jidian#80]
看了下词库里好多繁体字，实际不可能用这些繁体字，词库里的词太多还影响打字输出效率

**Comment by KyleBing** [comment]
目前应该是没有好的办法，因为 uinicode 字体集中，没有根据简繁进行区分，所以无法通过 unicode 范围进行筛选。
可行的方案只能是，找一个所有繁体字的集或简体字的集，然后将单字跟这两个中的任一一个比对进行筛选。

**Comment by chenzhiwei** [comment]
我这里维护了一个，里面应该是没繁体的：https://github.com/chenzhiwei/rime/tree/master/wubi
