### ISSUE TITLE
拼音混合输入，如何修改候选个数，缺省是5个

### ISSUE THREAD

**Issue by sztuxp** [KyleBing/rime-wubi86-jidian#86]
拼音混合输入，如何修改候选个数，缺省是5个

**Comment by KyleBing** [comment]
我还以为说明文件里有，结果发现没有，新添加了说明，照着修改即可。

[修改候选个数](https://github.com/KyleBing/rime-wubi86-jidian#1-%E5%80%99%E9%80%89%E4%B8%AA%E6%95%B0)
