### ISSUE TITLE
建议：默认配置觉得开启自动造词

### ISSUE THREAD

**Issue by seozed** [KyleBing/rime-wubi86-jidian#9]
我是在其它社区上看到有人推荐rime，然后下载来玩下，由于配置还是比较复杂的，一下也摸不到头绪，就想找个懒人包来配置。

github上搜索`rime wubi`，这个项目是排在第2的，第1是官方的wubi配置项目。

所以就选择了这个项目，导入配置后，发现无法输入法不会根据输入记录自造词，然后又在网上搜了一会，又翻了一下文档，才知道作者的的配置文件中默认把它关闭了。

这期间，我还以为rime输入法是没有这功能的，想着也太不成熟了，所以这项功能对于从其它输入法迁移过来的用户说，是习以为常的。

所以我建议建议配置中默认把这项功能给打开，或者在readme中添加开启造词的说明。

**Comment by KyleBing** [comment]
多谢建议。已经添加说明。

配置文件暂时没有修改的想法，该库主要尽可能的效仿 `极点五笔输入法` 的输入习惯：

1. 无重码时自动上屏
2. 4码上屏
3. 顶默认前词上屏
4. 固定词频

也是因为这些习惯才能保证五笔输入法可以高速输入。

**Comment by f1ynng8** [comment]
关于开启自动造词，赞同 @KyleBing 的想法，初始状态可以尽量模拟极点无笔的习惯。
不过今天在开启自动造词时，发现同时需要将db_class设置为userdb才可以，如果使用默认设置的tabledb，即使启用了自动造词开关也无法生效。建议这地方可以优化一下，方便用户自己开启自动造词。

**Comment by f1ynng8** [comment]
总结下来如果需要开启自动造词，需要将这些选项置为true：
```
  enable_user_dict: true               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: true                  # 自动造词
  encode_commit_history: true          # 是否对已上屏的词自动造词

```
@KyleBing encode_commit_history这个的注释应该是“是否对已上屏的词自动造词”，之前的注释有点歧义

**Comment by KyleBing** [comment]
@f1ynng8  已更正
