### ISSUE TITLE
请问是否可以实现自动联想功能

### ISSUE THREAD

**Issue by Juan-nikola** [KyleBing/rime-wubi86-jidian#98]
例如Mac原生输入法这样，打完一个字自动显示
<img width="721" alt="image" src="https://github.com/KyleBing/rime-wubi86-jidian/assets/74955200/cc5dc91c-983b-4321-8922-ea705e77f870">

**Comment by KyleBing** [comment]
五笔不考虑联想


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年6月12日 17:04 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [KyleBing/rime-wubi86-jidian] 请问是否可以实现自动联想功能 (Issue #98) |

例如Mac原生输入法这样，打完一个字自动显示

**Comment by Juan-nikola** [comment]
好吧好吧 确实鸡肋了

**Comment by Juan-nikola** [comment]
谢谢回复
